{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "c230ecf6-cddb-459d-a959-6a73a3ebad9b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting bitsandbytes==1.33.7rc0\n",
      "  Downloading https://github.com/bitsandbytes-foundation/bitsandbytes/releases/download/continuous-release_main/bitsandbytes-1.33.7.preview-py3-none-manylinux_2_24_x86_64.whl (62.3 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m62.3/62.3 MB\u001b[0m \u001b[31m117.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hInstalling collected packages: bitsandbytes\n",
      "  Attempting uninstall: bitsandbytes\n",
      "    Found existing installation: bitsandbytes 0.48.0.dev0\n",
      "    Uninstalling bitsandbytes-0.48.0.dev0:\n",
      "      Successfully uninstalled bitsandbytes-0.48.0.dev0\n",
      "Successfully installed bitsandbytes-0.48.0.dev0\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.\u001b[0m\u001b[33m\n",
      "\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m25.1.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m25.2\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpython3.12 -m pip install --upgrade pip\u001b[0m\n",
      "\u001b[33mWARNING: Skipping apex as it is not installed.\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.\u001b[0m\u001b[33m\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!pip install --no-deps --force-reinstall 'https://github.com/bitsandbytes-foundation/bitsandbytes/releases/download/continuous-release_main/bitsandbytes-1.33.7.preview-py3-none-manylinux_2_24_x86_64.whl'\n",
    "!pip uninstall apex\n",
    "# vllm doesn't validate rocm. need to check further."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a64a1196-a936-49ca-8ecb-73d25be6cb06",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO 09-27 10:17:16 [__init__.py:244] Automatically detected platform rocm.\n"
     ]
    }
   ],
   "source": [
    "import gc\n",
    "from typing import Optional\n",
    "\n",
    "import torch\n",
    "from huggingface_hub import snapshot_download\n",
    "\n",
    "from vllm import EngineArgs, LLMEngine, RequestOutput, SamplingParams\n",
    "from vllm.lora.request import LoRARequest"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "4c7eba0e-d93d-410d-9f68-4e311a08eb9a",
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_test_prompts(\n",
    "    lora_path: str,\n",
    ") -> list[tuple[str, SamplingParams, Optional[LoRARequest]]]:\n",
    "    return [\n",
    "        # this is an example of using quantization without LoRA\n",
    "        (\n",
    "            \"My name is\",\n",
    "            SamplingParams(\n",
    "                temperature=0.0, logprobs=1, prompt_logprobs=1, max_tokens=128\n",
    "            ),\n",
    "            None,\n",
    "        ),\n",
    "        # the next three examples use quantization with LoRA\n",
    "        (\n",
    "            \"my name is\",\n",
    "            SamplingParams(\n",
    "                temperature=0.0, logprobs=1, prompt_logprobs=1, max_tokens=128\n",
    "            ),\n",
    "            LoRARequest(\"lora-test-1\", 1, lora_path),\n",
    "        ),\n",
    "        (\n",
    "            \"The capital of USA is\",\n",
    "            SamplingParams(\n",
    "                temperature=0.0, logprobs=1, prompt_logprobs=1, max_tokens=128\n",
    "            ),\n",
    "            LoRARequest(\"lora-test-2\", 1, lora_path),\n",
    "        ),\n",
    "        (\n",
    "            \"The capital of France is\",\n",
    "            SamplingParams(\n",
    "                temperature=0.0, logprobs=1, prompt_logprobs=1, max_tokens=128\n",
    "            ),\n",
    "            LoRARequest(\"lora-test-3\", 1, lora_path),\n",
    "        ),\n",
    "    ]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "05f34804-f7c7-4aca-8087-16fe4439e3ef",
   "metadata": {},
   "outputs": [],
   "source": [
    "def process_requests(\n",
    "    engine: LLMEngine,\n",
    "    test_prompts: list[tuple[str, SamplingParams, Optional[LoRARequest]]],\n",
    "):\n",
    "    \"\"\"Continuously process a list of prompts and handle the outputs.\"\"\"\n",
    "    request_id = 0\n",
    "\n",
    "    while test_prompts or engine.has_unfinished_requests():\n",
    "        if test_prompts:\n",
    "            prompt, sampling_params, lora_request = test_prompts.pop(0)\n",
    "            engine.add_request(\n",
    "                str(request_id), prompt, sampling_params, lora_request=lora_request\n",
    "            )\n",
    "            request_id += 1\n",
    "\n",
    "        request_outputs: list[RequestOutput] = engine.step()\n",
    "        for request_output in request_outputs:\n",
    "            if request_output.finished:\n",
    "                print(\"----------------------------------------------------\")\n",
    "                print(f\"Prompt: {request_output.prompt}\")\n",
    "                print(f\"Output: {request_output.outputs[0].text}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "30b4cbe5-5d51-413d-a971-1b8f2eee2836",
   "metadata": {},
   "outputs": [],
   "source": [
    "def initialize_engine(\n",
    "    model: str, quantization: str, lora_repo: Optional[str]\n",
    ") -> LLMEngine:\n",
    "    \"\"\"Initialize the LLMEngine.\"\"\"\n",
    "\n",
    "    engine_args = EngineArgs(\n",
    "        model=model,\n",
    "        quantization=quantization,\n",
    "        enable_lora=True,\n",
    "        max_lora_rank=64,\n",
    "        max_loras=4,\n",
    "    )\n",
    "    return LLMEngine.from_engine_args(engine_args)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "2a263609-5046-431b-a8af-6f33a22698fb",
   "metadata": {},
   "outputs": [],
   "source": [
    "def main():\n",
    "    \"\"\"Main function that sets up and runs the prompt processing.\"\"\"\n",
    "\n",
    "    test_configs = [\n",
    "        # QLoRA (https://arxiv.org/abs/2305.14314)\n",
    "        # {\n",
    "        #     \"name\": \"qlora_inference_example\",\n",
    "        #     \"model\": \"huggyllama/llama-7b\",\n",
    "        #     \"quantization\": \"bitsandbytes\",\n",
    "        #     \"lora_repo\": \"timdettmers/qlora-flan-7b\",\n",
    "        # },\n",
    "        {\n",
    "            \"name\": \"AWQ_inference_with_lora_example\",\n",
    "            \"model\": \"TheBloke/TinyLlama-1.1B-Chat-v0.3-AWQ\",\n",
    "            \"quantization\": \"awq\",\n",
    "            \"lora_repo\": \"jashing/tinyllama-colorist-lora\",\n",
    "        },\n",
    "        {\n",
    "            \"name\": \"GPTQ_inference_with_lora_example\",\n",
    "            \"model\": \"TheBloke/TinyLlama-1.1B-Chat-v0.3-GPTQ\",\n",
    "            \"quantization\": \"gptq\",\n",
    "            \"lora_repo\": \"jashing/tinyllama-colorist-lora\",\n",
    "        },\n",
    "    ]\n",
    "\n",
    "    for test_config in test_configs:\n",
    "        print(f\"~~~~~~~~~~~~~~~~ Running: {test_config['name']} ~~~~~~~~~~~~~~~~\")\n",
    "        engine = initialize_engine(\n",
    "            test_config[\"model\"], test_config[\"quantization\"], test_config[\"lora_repo\"]\n",
    "        )\n",
    "        lora_path = snapshot_download(repo_id=test_config[\"lora_repo\"])\n",
    "        test_prompts = create_test_prompts(lora_path)\n",
    "        process_requests(engine, test_prompts)\n",
    "\n",
    "        # Clean up the GPU memory for the next test\n",
    "        # del engine\n",
    "        # gc.collect()\n",
    "        # torch.cuda.empty_cache()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "6a753044-1ce3-4133-b209-bd61849efdaa",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "~~~~~~~~~~~~~~~~ Running: AWQ_inference_with_lora_example ~~~~~~~~~~~~~~~~\n",
      "INFO 09-27 10:17:54 [config.py:853] This model supports multiple tasks: {'classify', 'generate', 'embed', 'score', 'reward'}. Defaulting to 'generate'.\n",
      "INFO 09-27 10:17:54 [config.py:1467] Using max model len 2048\n",
      "WARNING 09-27 10:18:04 [rocm.py:346] Using AWQ quantization with ROCm, but VLLM_USE_TRITON_AWQ is not set, enabling VLLM_USE_TRITON_AWQ.\n",
      "WARNING 09-27 10:18:04 [config.py:962] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.\n",
      "INFO 09-27 10:18:04 [config.py:2267] Chunked prefill is enabled with max_num_batched_tokens=2048.\n",
      "INFO 09-27 10:18:04 [config.py:4566] full_cuda_graph is not supported with cascade attention. Disabling cascade attention.\n",
      "WARNING 09-27 10:18:04 [utils.py:2613] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reason: CUDA is initialized\n",
      "INFO 09-27 10:18:07 [__init__.py:244] Automatically detected platform rocm.\n",
      "INFO 09-27 10:18:18 [core.py:459] Waiting for init message from front-end.\n",
      "INFO 09-27 10:18:18 [core.py:69] Initializing a V1 LLM engine (v0.9.2.dev364+gb432b7a28) with config: model='TheBloke/TinyLlama-1.1B-Chat-v0.3-AWQ', speculative_config=None, tokenizer='TheBloke/TinyLlama-1.1B-Chat-v0.3-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=awq, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=TheBloke/TinyLlama-1.1B-Chat-v0.3-AWQ, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={\"level\":3,\"debug_dump_path\":\"\",\"cache_dir\":\"\",\"backend\":\"\",\"custom_ops\":[\"+rms_norm\",\"+silu_and_mul\"],\"splitting_ops\":[],\"use_inductor\":true,\"compile_sizes\":[],\"inductor_compile_config\":{\"enable_auto_functionalized_v2\":false},\"inductor_passes\":{},\"use_cudagraph\":true,\"cudagraph_num_of_warmups\":1,\"cudagraph_capture_sizes\":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],\"cudagraph_copy_inputs\":false,\"full_cuda_graph\":true,\"max_capture_size\":512,\"local_cache_dir\":null}\n",
      "WARNING 09-27 10:18:19 [utils.py:2753] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x6ff840f49a00>\n",
      "INFO 09-27 10:18:19 [parallel_state.py:1076] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0\n",
      "INFO 09-27 10:18:19 [gpu_model_runner.py:1751] Starting to load model TheBloke/TinyLlama-1.1B-Chat-v0.3-AWQ...\n",
      "INFO 09-27 10:18:19 [gpu_model_runner.py:1756] Loading model from scratch...\n",
      "INFO 09-27 10:18:19 [rocm.py:224] Using Triton Attention backend on V1 engine.\n",
      "INFO 09-27 10:18:19 [weight_utils.py:292] Using model weights format ['*.safetensors']\n",
      "INFO 09-27 10:18:19 [weight_utils.py:345] No model.safetensors.index.json found in remote.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]\n",
      "Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  3.34it/s]\n",
      "Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  3.34it/s]\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO 09-27 10:18:20 [default_loader.py:272] Loading weights took 0.33 seconds\n",
      "INFO 09-27 10:18:20 [punica_selector.py:19] Using PunicaWrapperGPU.\n",
      "INFO 09-27 10:18:20 [gpu_model_runner.py:1782] Model loading took 1.1875 GiB and 0.758358 seconds\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Process EngineCore_0:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py\", line 523, in run_engine_core\n",
      "    raise e\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py\", line 510, in run_engine_core\n",
      "    engine_core = EngineCoreProc(*args, **kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py\", line 394, in __init__\n",
      "    super().__init__(vllm_config, executor_class, log_stats,\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py\", line 82, in __init__\n",
      "    self._initialize_kv_caches(vllm_config)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py\", line 142, in _initialize_kv_caches\n",
      "    available_gpu_memory = self.model_executor.determine_available_memory()\n",
      "                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/abstract.py\", line 76, in determine_available_memory\n",
      "    output = self.collective_rpc(\"determine_available_memory\")\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/executor/uniproc_executor.py\", line 57, in collective_rpc\n",
      "    answer = run_method(self.driver_worker, method, args, kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/utils.py\", line 2687, in run_method\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py\", line 116, in decorate_context\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_worker.py\", line 210, in determine_available_memory\n",
      "    self.model_runner.profile_run()\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py\", line 2257, in profile_run\n",
      "    = self._dummy_run(self.max_num_tokens, is_profile=True)\n",
      "      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py\", line 116, in decorate_context\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py\", line 2038, in _dummy_run\n",
      "    outputs = model(\n",
      "              ^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py\", line 1751, in _wrapped_call_impl\n",
      "    return self._call_impl(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py\", line 1762, in _call_impl\n",
      "    return forward_call(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/llama.py\", line 581, in forward\n",
      "    model_output = self.model(input_ids, positions, intermediate_tensors,\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py\", line 239, in __call__\n",
      "    output = self.compiled_callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py\", line 655, in _fn\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/convert_frame.py\", line 1432, in __call__\n",
      "    return self._torchdynamo_orig_callable(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/convert_frame.py\", line 598, in __call__\n",
      "    return _compile(\n",
      "           ^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/convert_frame.py\", line 1110, in _compile\n",
      "    raise InternalTorchDynamoError(\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/convert_frame.py\", line 1059, in _compile\n",
      "    guarded_code = compile_inner(code, one_graph, hooks, transform)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_utils_internal.py\", line 97, in wrapper_function\n",
      "    return function(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/convert_frame.py\", line 761, in compile_inner\n",
      "    return _compile_inner(code, one_graph, hooks, transform)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/convert_frame.py\", line 797, in _compile_inner\n",
      "    out_code = transform_code_object(code, transform)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/bytecode_transformation.py\", line 1422, in transform_code_object\n",
      "    transformations(instructions, code_options)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/convert_frame.py\", line 257, in _fn\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/convert_frame.py\", line 715, in transform\n",
      "    tracer.run()\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3500, in run\n",
      "    super().run()\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1337, in run\n",
      "    while self.step():\n",
      "          ^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1246, in step\n",
      "    self.dispatch_table[inst.opcode](self, inst)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 819, in wrapper\n",
      "    return inner_fn(self, inst)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2933, in CALL\n",
      "    self._call(inst)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2927, in _call\n",
      "    self.call_function(fn, args, kwargs)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1170, in call_function\n",
      "    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/nn_module.py\", line 952, in call_function\n",
      "    return variables.UserFunctionVariable(fn, source=source).call_function(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 404, in call_function\n",
      "    return super().call_function(tx, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 185, in call_function\n",
      "    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1187, in inline_user_function_return\n",
      "    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py\", line 235, in patched_inline_call\n",
      "    return inline_call(parent, func, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3726, in inline_call\n",
      "    return tracer.inline_call_()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3905, in inline_call_\n",
      "    self.run()\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1337, in run\n",
      "    while self.step():\n",
      "          ^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1246, in step\n",
      "    self.dispatch_table[inst.opcode](self, inst)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 819, in wrapper\n",
      "    return inner_fn(self, inst)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2933, in CALL\n",
      "    self._call(inst)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2927, in _call\n",
      "    self.call_function(fn, args, kwargs)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1170, in call_function\n",
      "    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/lazy.py\", line 201, in realize_and_forward\n",
      "    return getattr(self.realize(), name)(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/nn_module.py\", line 952, in call_function\n",
      "    return variables.UserFunctionVariable(fn, source=source).call_function(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 404, in call_function\n",
      "    return super().call_function(tx, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 185, in call_function\n",
      "    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1187, in inline_user_function_return\n",
      "    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py\", line 235, in patched_inline_call\n",
      "    return inline_call(parent, func, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3726, in inline_call\n",
      "    return tracer.inline_call_()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3905, in inline_call_\n",
      "    self.run()\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1337, in run\n",
      "    while self.step():\n",
      "          ^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1246, in step\n",
      "    self.dispatch_table[inst.opcode](self, inst)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 819, in wrapper\n",
      "    return inner_fn(self, inst)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2933, in CALL\n",
      "    self._call(inst)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2927, in _call\n",
      "    self.call_function(fn, args, kwargs)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1170, in call_function\n",
      "    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/lazy.py\", line 201, in realize_and_forward\n",
      "    return getattr(self.realize(), name)(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/nn_module.py\", line 952, in call_function\n",
      "    return variables.UserFunctionVariable(fn, source=source).call_function(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 404, in call_function\n",
      "    return super().call_function(tx, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 185, in call_function\n",
      "    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1187, in inline_user_function_return\n",
      "    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py\", line 235, in patched_inline_call\n",
      "    return inline_call(parent, func, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3726, in inline_call\n",
      "    return tracer.inline_call_()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3905, in inline_call_\n",
      "    self.run()\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1337, in run\n",
      "    while self.step():\n",
      "          ^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1246, in step\n",
      "    self.dispatch_table[inst.opcode](self, inst)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 819, in wrapper\n",
      "    return inner_fn(self, inst)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2933, in CALL\n",
      "    self._call(inst)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2927, in _call\n",
      "    self.call_function(fn, args, kwargs)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1170, in call_function\n",
      "    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 926, in call_function\n",
      "    return super().call_function(tx, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 404, in call_function\n",
      "    return super().call_function(tx, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 185, in call_function\n",
      "    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1187, in inline_user_function_return\n",
      "    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py\", line 235, in patched_inline_call\n",
      "    return inline_call(parent, func, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3726, in inline_call\n",
      "    return tracer.inline_call_()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3905, in inline_call_\n",
      "    self.run()\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1337, in run\n",
      "    while self.step():\n",
      "          ^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1246, in step\n",
      "    self.dispatch_table[inst.opcode](self, inst)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 819, in wrapper\n",
      "    return inner_fn(self, inst)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2933, in CALL\n",
      "    self._call(inst)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2927, in _call\n",
      "    self.call_function(fn, args, kwargs)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1170, in call_function\n",
      "    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 926, in call_function\n",
      "    return super().call_function(tx, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 404, in call_function\n",
      "    return super().call_function(tx, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 185, in call_function\n",
      "    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1187, in inline_user_function_return\n",
      "    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py\", line 235, in patched_inline_call\n",
      "    return inline_call(parent, func, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3726, in inline_call\n",
      "    return tracer.inline_call_()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3905, in inline_call_\n",
      "    self.run()\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1337, in run\n",
      "    while self.step():\n",
      "          ^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1246, in step\n",
      "    self.dispatch_table[inst.opcode](self, inst)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 819, in wrapper\n",
      "    return inner_fn(self, inst)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2933, in CALL\n",
      "    self._call(inst)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2927, in _call\n",
      "    self.call_function(fn, args, kwargs)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1170, in call_function\n",
      "    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 404, in call_function\n",
      "    return super().call_function(tx, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 185, in call_function\n",
      "    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1187, in inline_user_function_return\n",
      "    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py\", line 235, in patched_inline_call\n",
      "    return inline_call(parent, func, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3726, in inline_call\n",
      "    return tracer.inline_call_()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3905, in inline_call_\n",
      "    self.run()\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1337, in run\n",
      "    while self.step():\n",
      "          ^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1246, in step\n",
      "    self.dispatch_table[inst.opcode](self, inst)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2330, in LOAD_ATTR\n",
      "    self.LOAD_METHOD(inst)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2296, in LOAD_METHOD\n",
      "    self._load_attr(inst)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2320, in _load_attr\n",
      "    result = BuiltinVariable(getattr).call_function(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/builtin.py\", line 1111, in call_function\n",
      "    return handler(tx, args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/builtin.py\", line 945, in builtin_dispatch\n",
      "    rv = fn(tx, args, kwargs)\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/builtin.py\", line 850, in call_self_handler\n",
      "    result = self_handler(tx, *args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/builtin.py\", line 1897, in call_getattr\n",
      "    return obj.var_getattr(tx, name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/misc.py\", line 1065, in var_getattr\n",
      "    attr_value = getattr(self.value, name)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/torch/_ops.py\", line 1267, in __getattr__\n",
      "    raise AttributeError(\n",
      "torch._dynamo.exc.InternalTorchDynamoError: AttributeError: '_OpNamespace' '_C' object has no attribute 'awq_dequantize'\n",
      "\n",
      "from user code:\n",
      "   File \"/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/llama.py\", line 392, in forward\n",
      "    hidden_states, residual = layer(positions, hidden_states, residual)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/llama.py\", line 305, in forward\n",
      "    hidden_states = self.self_attn(positions=positions,\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/llama.py\", line 200, in forward\n",
      "    qkv, _ = self.qkv_proj(hidden_states)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/lora/layers.py\", line 581, in forward\n",
      "    output_parallel = self.apply(input_, bias)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/lora/layers.py\", line 412, in apply\n",
      "    output = self.base_layer.quant_method.apply(self.base_layer, x, bias)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/quantization/awq.py\", line 221, in apply\n",
      "    out = ops.awq_dequantize(qweight, scales, qzeros, 0, 0, 0)\n",
      "  File \"/usr/local/lib/python3.12/dist-packages/vllm/_custom_ops.py\", line 389, in awq_dequantize\n",
      "    return torch.ops._C.awq_dequantize(qweight, scales, zeros, split_k_iters,\n",
      "\n",
      "Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS=\"+dynamo\"\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ERROR 09-27 10:18:21 [core.py:519] EngineCore failed to start.\n",
      "ERROR 09-27 10:18:21 [core.py:519] Traceback (most recent call last):\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py\", line 510, in run_engine_core\n",
      "ERROR 09-27 10:18:21 [core.py:519]     engine_core = EngineCoreProc(*args, **kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py\", line 394, in __init__\n",
      "ERROR 09-27 10:18:21 [core.py:519]     super().__init__(vllm_config, executor_class, log_stats,\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py\", line 82, in __init__\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self._initialize_kv_caches(vllm_config)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py\", line 142, in _initialize_kv_caches\n",
      "ERROR 09-27 10:18:21 [core.py:519]     available_gpu_memory = self.model_executor.determine_available_memory()\n",
      "ERROR 09-27 10:18:21 [core.py:519]                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/abstract.py\", line 76, in determine_available_memory\n",
      "ERROR 09-27 10:18:21 [core.py:519]     output = self.collective_rpc(\"determine_available_memory\")\n",
      "ERROR 09-27 10:18:21 [core.py:519]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/executor/uniproc_executor.py\", line 57, in collective_rpc\n",
      "ERROR 09-27 10:18:21 [core.py:519]     answer = run_method(self.driver_worker, method, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/utils.py\", line 2687, in run_method\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return func(*args, **kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py\", line 116, in decorate_context\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return func(*args, **kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_worker.py\", line 210, in determine_available_memory\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.model_runner.profile_run()\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py\", line 2257, in profile_run\n",
      "ERROR 09-27 10:18:21 [core.py:519]     = self._dummy_run(self.max_num_tokens, is_profile=True)\n",
      "ERROR 09-27 10:18:21 [core.py:519]       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py\", line 116, in decorate_context\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return func(*args, **kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py\", line 2038, in _dummy_run\n",
      "ERROR 09-27 10:18:21 [core.py:519]     outputs = model(\n",
      "ERROR 09-27 10:18:21 [core.py:519]               ^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py\", line 1751, in _wrapped_call_impl\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return self._call_impl(*args, **kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py\", line 1762, in _call_impl\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return forward_call(*args, **kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/llama.py\", line 581, in forward\n",
      "ERROR 09-27 10:18:21 [core.py:519]     model_output = self.model(input_ids, positions, intermediate_tensors,\n",
      "ERROR 09-27 10:18:21 [core.py:519]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py\", line 239, in __call__\n",
      "ERROR 09-27 10:18:21 [core.py:519]     output = self.compiled_callable(*args, **kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py\", line 655, in _fn\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return fn(*args, **kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/convert_frame.py\", line 1432, in __call__\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return self._torchdynamo_orig_callable(\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/convert_frame.py\", line 598, in __call__\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return _compile(\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/convert_frame.py\", line 1110, in _compile\n",
      "ERROR 09-27 10:18:21 [core.py:519]     raise InternalTorchDynamoError(\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/convert_frame.py\", line 1059, in _compile\n",
      "ERROR 09-27 10:18:21 [core.py:519]     guarded_code = compile_inner(code, one_graph, hooks, transform)\n",
      "ERROR 09-27 10:18:21 [core.py:519]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_utils_internal.py\", line 97, in wrapper_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return function(*args, **kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/convert_frame.py\", line 761, in compile_inner\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return _compile_inner(code, one_graph, hooks, transform)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/convert_frame.py\", line 797, in _compile_inner\n",
      "ERROR 09-27 10:18:21 [core.py:519]     out_code = transform_code_object(code, transform)\n",
      "ERROR 09-27 10:18:21 [core.py:519]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/bytecode_transformation.py\", line 1422, in transform_code_object\n",
      "ERROR 09-27 10:18:21 [core.py:519]     transformations(instructions, code_options)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/convert_frame.py\", line 257, in _fn\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return fn(*args, **kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/convert_frame.py\", line 715, in transform\n",
      "ERROR 09-27 10:18:21 [core.py:519]     tracer.run()\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3500, in run\n",
      "ERROR 09-27 10:18:21 [core.py:519]     super().run()\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1337, in run\n",
      "ERROR 09-27 10:18:21 [core.py:519]     while self.step():\n",
      "ERROR 09-27 10:18:21 [core.py:519]           ^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1246, in step\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.dispatch_table[inst.opcode](self, inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 819, in wrapper\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return inner_fn(self, inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2933, in CALL\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self._call(inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2927, in _call\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.call_function(fn, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1170, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]\n",
      "ERROR 09-27 10:18:21 [core.py:519]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/nn_module.py\", line 952, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return variables.UserFunctionVariable(fn, source=source).call_function(\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 404, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return super().call_function(tx, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 185, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1187, in inline_user_function_return\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py\", line 235, in patched_inline_call\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return inline_call(parent, func, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3726, in inline_call\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return tracer.inline_call_()\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3905, in inline_call_\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.run()\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1337, in run\n",
      "ERROR 09-27 10:18:21 [core.py:519]     while self.step():\n",
      "ERROR 09-27 10:18:21 [core.py:519]           ^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1246, in step\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.dispatch_table[inst.opcode](self, inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 819, in wrapper\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return inner_fn(self, inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2933, in CALL\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self._call(inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2927, in _call\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.call_function(fn, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1170, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]\n",
      "ERROR 09-27 10:18:21 [core.py:519]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/lazy.py\", line 201, in realize_and_forward\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return getattr(self.realize(), name)(*args, **kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/nn_module.py\", line 952, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return variables.UserFunctionVariable(fn, source=source).call_function(\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 404, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return super().call_function(tx, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 185, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1187, in inline_user_function_return\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py\", line 235, in patched_inline_call\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return inline_call(parent, func, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3726, in inline_call\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return tracer.inline_call_()\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3905, in inline_call_\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.run()\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1337, in run\n",
      "ERROR 09-27 10:18:21 [core.py:519]     while self.step():\n",
      "ERROR 09-27 10:18:21 [core.py:519]           ^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1246, in step\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.dispatch_table[inst.opcode](self, inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 819, in wrapper\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return inner_fn(self, inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2933, in CALL\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self._call(inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2927, in _call\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.call_function(fn, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1170, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]\n",
      "ERROR 09-27 10:18:21 [core.py:519]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/lazy.py\", line 201, in realize_and_forward\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return getattr(self.realize(), name)(*args, **kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/nn_module.py\", line 952, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return variables.UserFunctionVariable(fn, source=source).call_function(\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 404, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return super().call_function(tx, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 185, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1187, in inline_user_function_return\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py\", line 235, in patched_inline_call\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return inline_call(parent, func, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3726, in inline_call\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return tracer.inline_call_()\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3905, in inline_call_\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.run()\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1337, in run\n",
      "ERROR 09-27 10:18:21 [core.py:519]     while self.step():\n",
      "ERROR 09-27 10:18:21 [core.py:519]           ^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1246, in step\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.dispatch_table[inst.opcode](self, inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 819, in wrapper\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return inner_fn(self, inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2933, in CALL\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self._call(inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2927, in _call\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.call_function(fn, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1170, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]\n",
      "ERROR 09-27 10:18:21 [core.py:519]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 926, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return super().call_function(tx, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 404, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return super().call_function(tx, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 185, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1187, in inline_user_function_return\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py\", line 235, in patched_inline_call\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return inline_call(parent, func, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3726, in inline_call\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return tracer.inline_call_()\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3905, in inline_call_\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.run()\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1337, in run\n",
      "ERROR 09-27 10:18:21 [core.py:519]     while self.step():\n",
      "ERROR 09-27 10:18:21 [core.py:519]           ^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1246, in step\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.dispatch_table[inst.opcode](self, inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 819, in wrapper\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return inner_fn(self, inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2933, in CALL\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self._call(inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2927, in _call\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.call_function(fn, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1170, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]\n",
      "ERROR 09-27 10:18:21 [core.py:519]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 926, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return super().call_function(tx, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 404, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return super().call_function(tx, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 185, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1187, in inline_user_function_return\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py\", line 235, in patched_inline_call\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return inline_call(parent, func, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3726, in inline_call\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return tracer.inline_call_()\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3905, in inline_call_\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.run()\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1337, in run\n",
      "ERROR 09-27 10:18:21 [core.py:519]     while self.step():\n",
      "ERROR 09-27 10:18:21 [core.py:519]           ^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1246, in step\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.dispatch_table[inst.opcode](self, inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 819, in wrapper\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return inner_fn(self, inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2933, in CALL\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self._call(inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2927, in _call\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.call_function(fn, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1170, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]\n",
      "ERROR 09-27 10:18:21 [core.py:519]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 404, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return super().call_function(tx, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/functions.py\", line 185, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1187, in inline_user_function_return\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py\", line 235, in patched_inline_call\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return inline_call(parent, func, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3726, in inline_call\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return tracer.inline_call_()\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 3905, in inline_call_\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.run()\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1337, in run\n",
      "ERROR 09-27 10:18:21 [core.py:519]     while self.step():\n",
      "ERROR 09-27 10:18:21 [core.py:519]           ^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 1246, in step\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.dispatch_table[inst.opcode](self, inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2330, in LOAD_ATTR\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self.LOAD_METHOD(inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2296, in LOAD_METHOD\n",
      "ERROR 09-27 10:18:21 [core.py:519]     self._load_attr(inst)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/symbolic_convert.py\", line 2320, in _load_attr\n",
      "ERROR 09-27 10:18:21 [core.py:519]     result = BuiltinVariable(getattr).call_function(\n",
      "ERROR 09-27 10:18:21 [core.py:519]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/builtin.py\", line 1111, in call_function\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return handler(tx, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/builtin.py\", line 945, in builtin_dispatch\n",
      "ERROR 09-27 10:18:21 [core.py:519]     rv = fn(tx, args, kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]          ^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/builtin.py\", line 850, in call_self_handler\n",
      "ERROR 09-27 10:18:21 [core.py:519]     result = self_handler(tx, *args, **kwargs)\n",
      "ERROR 09-27 10:18:21 [core.py:519]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/builtin.py\", line 1897, in call_getattr\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return obj.var_getattr(tx, name)\n",
      "ERROR 09-27 10:18:21 [core.py:519]            ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_dynamo/variables/misc.py\", line 1065, in var_getattr\n",
      "ERROR 09-27 10:18:21 [core.py:519]     attr_value = getattr(self.value, name)\n",
      "ERROR 09-27 10:18:21 [core.py:519]                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/torch/_ops.py\", line 1267, in __getattr__\n",
      "ERROR 09-27 10:18:21 [core.py:519]     raise AttributeError(\n",
      "ERROR 09-27 10:18:21 [core.py:519] torch._dynamo.exc.InternalTorchDynamoError: AttributeError: '_OpNamespace' '_C' object has no attribute 'awq_dequantize'\n",
      "ERROR 09-27 10:18:21 [core.py:519] \n",
      "ERROR 09-27 10:18:21 [core.py:519] from user code:\n",
      "ERROR 09-27 10:18:21 [core.py:519]    File \"/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/llama.py\", line 392, in forward\n",
      "ERROR 09-27 10:18:21 [core.py:519]     hidden_states, residual = layer(positions, hidden_states, residual)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/llama.py\", line 305, in forward\n",
      "ERROR 09-27 10:18:21 [core.py:519]     hidden_states = self.self_attn(positions=positions,\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/llama.py\", line 200, in forward\n",
      "ERROR 09-27 10:18:21 [core.py:519]     qkv, _ = self.qkv_proj(hidden_states)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/lora/layers.py\", line 581, in forward\n",
      "ERROR 09-27 10:18:21 [core.py:519]     output_parallel = self.apply(input_, bias)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/lora/layers.py\", line 412, in apply\n",
      "ERROR 09-27 10:18:21 [core.py:519]     output = self.base_layer.quant_method.apply(self.base_layer, x, bias)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/quantization/awq.py\", line 221, in apply\n",
      "ERROR 09-27 10:18:21 [core.py:519]     out = ops.awq_dequantize(qweight, scales, qzeros, 0, 0, 0)\n",
      "ERROR 09-27 10:18:21 [core.py:519]   File \"/usr/local/lib/python3.12/dist-packages/vllm/_custom_ops.py\", line 389, in awq_dequantize\n",
      "ERROR 09-27 10:18:21 [core.py:519]     return torch.ops._C.awq_dequantize(qweight, scales, zeros, split_k_iters,\n",
      "ERROR 09-27 10:18:21 [core.py:519] \n",
      "ERROR 09-27 10:18:21 [core.py:519] Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS=\"+dynamo\"\n",
      "ERROR 09-27 10:18:21 [core.py:519] \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[rank0]:[W927 10:18:21.369484922 ProcessGroupNCCL.cpp:1476] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())\n"
     ]
    },
    {
     "ename": "RuntimeError",
     "evalue": "Engine core initialization failed. See root cause above. Failed core proc(s): {}",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mRuntimeError\u001b[39m                              Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[6]\u001b[39m\u001b[32m, line 1\u001b[39m\n\u001b[32m----> \u001b[39m\u001b[32m1\u001b[39m \u001b[43mmain\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[5]\u001b[39m\u001b[32m, line 28\u001b[39m, in \u001b[36mmain\u001b[39m\u001b[34m()\u001b[39m\n\u001b[32m     26\u001b[39m \u001b[38;5;28;01mfor\u001b[39;00m test_config \u001b[38;5;129;01min\u001b[39;00m test_configs:\n\u001b[32m     27\u001b[39m     \u001b[38;5;28mprint\u001b[39m(\u001b[33mf\u001b[39m\u001b[33m\"\u001b[39m\u001b[33m~~~~~~~~~~~~~~~~ Running: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mtest_config[\u001b[33m'\u001b[39m\u001b[33mname\u001b[39m\u001b[33m'\u001b[39m]\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m ~~~~~~~~~~~~~~~~\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m---> \u001b[39m\u001b[32m28\u001b[39m     engine = \u001b[43minitialize_engine\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m     29\u001b[39m \u001b[43m        \u001b[49m\u001b[43mtest_config\u001b[49m\u001b[43m[\u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mmodel\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtest_config\u001b[49m\u001b[43m[\u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mquantization\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtest_config\u001b[49m\u001b[43m[\u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mlora_repo\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m]\u001b[49m\n\u001b[32m     30\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m     31\u001b[39m     lora_path = snapshot_download(repo_id=test_config[\u001b[33m\"\u001b[39m\u001b[33mlora_repo\u001b[39m\u001b[33m\"\u001b[39m])\n\u001b[32m     32\u001b[39m     test_prompts = create_test_prompts(lora_path)\n",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[4]\u001b[39m\u001b[32m, line 13\u001b[39m, in \u001b[36minitialize_engine\u001b[39m\u001b[34m(model, quantization, lora_repo)\u001b[39m\n\u001b[32m      4\u001b[39m \u001b[38;5;250m\u001b[39m\u001b[33;03m\"\"\"Initialize the LLMEngine.\"\"\"\u001b[39;00m\n\u001b[32m      6\u001b[39m engine_args = EngineArgs(\n\u001b[32m      7\u001b[39m     model=model,\n\u001b[32m      8\u001b[39m     quantization=quantization,\n\u001b[32m   (...)\u001b[39m\u001b[32m     11\u001b[39m     max_loras=\u001b[32m4\u001b[39m,\n\u001b[32m     12\u001b[39m )\n\u001b[32m---> \u001b[39m\u001b[32m13\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mLLMEngine\u001b[49m\u001b[43m.\u001b[49m\u001b[43mfrom_engine_args\u001b[49m\u001b[43m(\u001b[49m\u001b[43mengine_args\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py:501\u001b[39m, in \u001b[36mLLMEngine.from_engine_args\u001b[39m\u001b[34m(cls, engine_args, usage_context, stat_loggers)\u001b[39m\n\u001b[32m    498\u001b[39m     \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mvllm\u001b[39;00m\u001b[34;01m.\u001b[39;00m\u001b[34;01mv1\u001b[39;00m\u001b[34;01m.\u001b[39;00m\u001b[34;01mengine\u001b[39;00m\u001b[34;01m.\u001b[39;00m\u001b[34;01mllm_engine\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m LLMEngine \u001b[38;5;28;01mas\u001b[39;00m V1LLMEngine\n\u001b[32m    499\u001b[39m     engine_cls = V1LLMEngine\n\u001b[32m--> \u001b[39m\u001b[32m501\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mengine_cls\u001b[49m\u001b[43m.\u001b[49m\u001b[43mfrom_vllm_config\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    502\u001b[39m \u001b[43m    \u001b[49m\u001b[43mvllm_config\u001b[49m\u001b[43m=\u001b[49m\u001b[43mvllm_config\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    503\u001b[39m \u001b[43m    \u001b[49m\u001b[43musage_context\u001b[49m\u001b[43m=\u001b[49m\u001b[43musage_context\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    504\u001b[39m \u001b[43m    \u001b[49m\u001b[43mstat_loggers\u001b[49m\u001b[43m=\u001b[49m\u001b[43mstat_loggers\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    505\u001b[39m \u001b[43m    \u001b[49m\u001b[43mdisable_log_stats\u001b[49m\u001b[43m=\u001b[49m\u001b[43mengine_args\u001b[49m\u001b[43m.\u001b[49m\u001b[43mdisable_log_stats\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    506\u001b[39m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/llm_engine.py:124\u001b[39m, in \u001b[36mLLMEngine.from_vllm_config\u001b[39m\u001b[34m(cls, vllm_config, usage_context, stat_loggers, disable_log_stats)\u001b[39m\n\u001b[32m    116\u001b[39m \u001b[38;5;129m@classmethod\u001b[39m\n\u001b[32m    117\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mfrom_vllm_config\u001b[39m(\n\u001b[32m    118\u001b[39m     \u001b[38;5;28mcls\u001b[39m,\n\u001b[32m   (...)\u001b[39m\u001b[32m    122\u001b[39m     disable_log_stats: \u001b[38;5;28mbool\u001b[39m = \u001b[38;5;28;01mFalse\u001b[39;00m,\n\u001b[32m    123\u001b[39m ) -> \u001b[33m\"\u001b[39m\u001b[33mLLMEngine\u001b[39m\u001b[33m\"\u001b[39m:\n\u001b[32m--> \u001b[39m\u001b[32m124\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mcls\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mvllm_config\u001b[49m\u001b[43m=\u001b[49m\u001b[43mvllm_config\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    125\u001b[39m \u001b[43m               \u001b[49m\u001b[43mexecutor_class\u001b[49m\u001b[43m=\u001b[49m\u001b[43mExecutor\u001b[49m\u001b[43m.\u001b[49m\u001b[43mget_class\u001b[49m\u001b[43m(\u001b[49m\u001b[43mvllm_config\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    126\u001b[39m \u001b[43m               \u001b[49m\u001b[43mlog_stats\u001b[49m\u001b[43m=\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;129;43;01mnot\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mdisable_log_stats\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    127\u001b[39m \u001b[43m               \u001b[49m\u001b[43musage_context\u001b[49m\u001b[43m=\u001b[49m\u001b[43musage_context\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    128\u001b[39m \u001b[43m               \u001b[49m\u001b[43mstat_loggers\u001b[49m\u001b[43m=\u001b[49m\u001b[43mstat_loggers\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    129\u001b[39m \u001b[43m               \u001b[49m\u001b[43mmultiprocess_mode\u001b[49m\u001b[43m=\u001b[49m\u001b[43menvs\u001b[49m\u001b[43m.\u001b[49m\u001b[43mVLLM_ENABLE_V1_MULTIPROCESSING\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/llm_engine.py:101\u001b[39m, in \u001b[36mLLMEngine.__init__\u001b[39m\u001b[34m(self, vllm_config, executor_class, log_stats, usage_context, stat_loggers, mm_registry, use_cached_outputs, multiprocess_mode)\u001b[39m\n\u001b[32m     97\u001b[39m \u001b[38;5;28mself\u001b[39m.output_processor = OutputProcessor(\u001b[38;5;28mself\u001b[39m.tokenizer,\n\u001b[32m     98\u001b[39m                                         log_stats=\u001b[38;5;28mself\u001b[39m.log_stats)\n\u001b[32m    100\u001b[39m \u001b[38;5;66;03m# EngineCore (gets EngineCoreRequests and gives EngineCoreOutputs)\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m101\u001b[39m \u001b[38;5;28mself\u001b[39m.engine_core = \u001b[43mEngineCoreClient\u001b[49m\u001b[43m.\u001b[49m\u001b[43mmake_client\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    102\u001b[39m \u001b[43m    \u001b[49m\u001b[43mmultiprocess_mode\u001b[49m\u001b[43m=\u001b[49m\u001b[43mmultiprocess_mode\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    103\u001b[39m \u001b[43m    \u001b[49m\u001b[43masyncio_mode\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[32m    104\u001b[39m \u001b[43m    \u001b[49m\u001b[43mvllm_config\u001b[49m\u001b[43m=\u001b[49m\u001b[43mvllm_config\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    105\u001b[39m \u001b[43m    \u001b[49m\u001b[43mexecutor_class\u001b[49m\u001b[43m=\u001b[49m\u001b[43mexecutor_class\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    106\u001b[39m \u001b[43m    \u001b[49m\u001b[43mlog_stats\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mlog_stats\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    107\u001b[39m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    109\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m multiprocess_mode:\n\u001b[32m    110\u001b[39m     \u001b[38;5;66;03m# for v0 compatibility\u001b[39;00m\n\u001b[32m    111\u001b[39m     \u001b[38;5;28mself\u001b[39m.model_executor = \u001b[38;5;28mself\u001b[39m.engine_core.engine_core.model_executor  \u001b[38;5;66;03m# type: ignore\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py:75\u001b[39m, in \u001b[36mEngineCoreClient.make_client\u001b[39m\u001b[34m(multiprocess_mode, asyncio_mode, vllm_config, executor_class, log_stats)\u001b[39m\n\u001b[32m     71\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m EngineCoreClient.make_async_mp_client(\n\u001b[32m     72\u001b[39m         vllm_config, executor_class, log_stats)\n\u001b[32m     74\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m multiprocess_mode \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m asyncio_mode:\n\u001b[32m---> \u001b[39m\u001b[32m75\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mSyncMPClient\u001b[49m\u001b[43m(\u001b[49m\u001b[43mvllm_config\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mexecutor_class\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mlog_stats\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m     77\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m InprocClient(vllm_config, executor_class, log_stats)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py:572\u001b[39m, in \u001b[36mSyncMPClient.__init__\u001b[39m\u001b[34m(self, vllm_config, executor_class, log_stats)\u001b[39m\n\u001b[32m    570\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m__init__\u001b[39m(\u001b[38;5;28mself\u001b[39m, vllm_config: VllmConfig, executor_class: \u001b[38;5;28mtype\u001b[39m[Executor],\n\u001b[32m    571\u001b[39m              log_stats: \u001b[38;5;28mbool\u001b[39m):\n\u001b[32m--> \u001b[39m\u001b[32m572\u001b[39m     \u001b[38;5;28;43msuper\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m.\u001b[49m\u001b[34;43m__init__\u001b[39;49m\u001b[43m(\u001b[49m\n\u001b[32m    573\u001b[39m \u001b[43m        \u001b[49m\u001b[43masyncio_mode\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[32m    574\u001b[39m \u001b[43m        \u001b[49m\u001b[43mvllm_config\u001b[49m\u001b[43m=\u001b[49m\u001b[43mvllm_config\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    575\u001b[39m \u001b[43m        \u001b[49m\u001b[43mexecutor_class\u001b[49m\u001b[43m=\u001b[49m\u001b[43mexecutor_class\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    576\u001b[39m \u001b[43m        \u001b[49m\u001b[43mlog_stats\u001b[49m\u001b[43m=\u001b[49m\u001b[43mlog_stats\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    577\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    579\u001b[39m     \u001b[38;5;28mself\u001b[39m.is_dp = \u001b[38;5;28mself\u001b[39m.vllm_config.parallel_config.data_parallel_size > \u001b[32m1\u001b[39m\n\u001b[32m    580\u001b[39m     \u001b[38;5;28mself\u001b[39m.outputs_queue = queue.Queue[Union[EngineCoreOutputs, \u001b[38;5;167;01mException\u001b[39;00m]]()\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py:433\u001b[39m, in \u001b[36mMPClient.__init__\u001b[39m\u001b[34m(self, asyncio_mode, vllm_config, executor_class, log_stats, client_addresses)\u001b[39m\n\u001b[32m    429\u001b[39m \u001b[38;5;28mself\u001b[39m.resources.output_socket = make_zmq_socket(\n\u001b[32m    430\u001b[39m     \u001b[38;5;28mself\u001b[39m.ctx, output_address, zmq.PULL)\n\u001b[32m    432\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m client_addresses \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m433\u001b[39m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_init_engines_direct\u001b[49m\u001b[43m(\u001b[49m\u001b[43mvllm_config\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mlocal_only\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    434\u001b[39m \u001b[43m                              \u001b[49m\u001b[43mlocal_start_index\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43minput_address\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    435\u001b[39m \u001b[43m                              \u001b[49m\u001b[43moutput_address\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mexecutor_class\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    436\u001b[39m \u001b[43m                              \u001b[49m\u001b[43mlog_stats\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    437\u001b[39m     coordinator = \u001b[38;5;28mself\u001b[39m.resources.coordinator\n\u001b[32m    438\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m coordinator:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py:502\u001b[39m, in \u001b[36mMPClient._init_engines_direct\u001b[39m\u001b[34m(self, vllm_config, local_only, local_start_index, input_address, output_address, executor_class, log_stats)\u001b[39m\n\u001b[32m    490\u001b[39m     \u001b[38;5;28mself\u001b[39m.resources.engine_manager = CoreEngineProcManager(\n\u001b[32m    491\u001b[39m         EngineCoreProc.run_engine_core,\n\u001b[32m    492\u001b[39m         vllm_config=vllm_config,\n\u001b[32m   (...)\u001b[39m\u001b[32m    498\u001b[39m         start_index=start_index,\n\u001b[32m    499\u001b[39m         local_start_index=local_start_index)\n\u001b[32m    501\u001b[39m \u001b[38;5;66;03m# Wait for engine core process(es) to start.\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m502\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_wait_for_engine_startup\u001b[49m\u001b[43m(\u001b[49m\u001b[43mhandshake_socket\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43minput_address\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    503\u001b[39m \u001b[43m                              \u001b[49m\u001b[43moutput_address\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py:522\u001b[39m, in \u001b[36mMPClient._wait_for_engine_startup\u001b[39m\u001b[34m(self, handshake_socket, input_address, output_address)\u001b[39m\n\u001b[32m    517\u001b[39m proc_manager = \u001b[38;5;28mself\u001b[39m.resources.engine_manager\n\u001b[32m    518\u001b[39m \u001b[38;5;28;01massert\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(proc_manager, (\u001b[38;5;28mtype\u001b[39m(\u001b[38;5;28;01mNone\u001b[39;00m), CoreEngineProcManager)), (\n\u001b[32m    519\u001b[39m     \u001b[33m\"\u001b[39m\u001b[33m_wait_for_engine_startup should only be \u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m    520\u001b[39m     \u001b[33m\"\u001b[39m\u001b[33mcalled with CoreEngineProcManager\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m--> \u001b[39m\u001b[32m522\u001b[39m \u001b[43mwait_for_engine_startup\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    523\u001b[39m \u001b[43m    \u001b[49m\u001b[43mhandshake_socket\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    524\u001b[39m \u001b[43m    \u001b[49m\u001b[43maddresses\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    525\u001b[39m \u001b[43m    \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mcore_engines\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    526\u001b[39m \u001b[43m    \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mvllm_config\u001b[49m\u001b[43m.\u001b[49m\u001b[43mparallel_config\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    527\u001b[39m \u001b[43m    \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mvllm_config\u001b[49m\u001b[43m.\u001b[49m\u001b[43mcache_config\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    528\u001b[39m \u001b[43m    \u001b[49m\u001b[43mproc_manager\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    529\u001b[39m \u001b[43m    \u001b[49m\u001b[43mcoordinator\u001b[49m\u001b[43m.\u001b[49m\u001b[43mproc\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mif\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mcoordinator\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01melse\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mNone\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[32m    530\u001b[39m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/usr/local/lib/python3.12/dist-packages/vllm/v1/utils.py:494\u001b[39m, in \u001b[36mwait_for_engine_startup\u001b[39m\u001b[34m(handshake_socket, addresses, core_engines, parallel_config, cache_config, proc_manager, coord_process)\u001b[39m\n\u001b[32m    492\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m coord_process \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;129;01mand\u001b[39;00m coord_process.exitcode \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m    493\u001b[39m         finished[coord_process.name] = coord_process.exitcode\n\u001b[32m--> \u001b[39m\u001b[32m494\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mRuntimeError\u001b[39;00m(\u001b[33m\"\u001b[39m\u001b[33mEngine core initialization failed. \u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m    495\u001b[39m                        \u001b[33m\"\u001b[39m\u001b[33mSee root cause above. \u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m    496\u001b[39m                        \u001b[33mf\u001b[39m\u001b[33m\"\u001b[39m\u001b[33mFailed core proc(s): \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mfinished\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m\"\u001b[39m)\n\u001b[32m    498\u001b[39m \u001b[38;5;66;03m# Receive HELLO and READY messages from the input socket.\u001b[39;00m\n\u001b[32m    499\u001b[39m eng_identity, ready_msg_bytes = handshake_socket.recv_multipart()\n",
      "\u001b[31mRuntimeError\u001b[39m: Engine core initialization failed. See root cause above. Failed core proc(s): {}"
     ]
    }
   ],
   "source": [
    "main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1c6fd473-2f2d-406e-81a7-0bc3a9083f51",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
